"""Add profile fields to borrower model

Revision ID: a460de563207
Revises:
Create Date: 2025-07-16 11:35:22.916196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a460de563207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrower_profiles')
    op.drop_table('loan_applications')
    op.drop_table('profile_documents')
    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bvn', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('nin', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('primary_id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('primary_id_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('work_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_purpose', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('loan_term', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_collateral', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('collateral_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('collateral_value', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('collateral_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guarantor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guarantor_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guarantor_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guarantor_relationship', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('guarantor_relationship')
        batch_op.drop_column('guarantor_address')
        batch_op.drop_column('guarantor_phone')
        batch_op.drop_column('guarantor_name')
        batch_op.drop_column('collateral_description')
        batch_op.drop_column('collateral_value')
        batch_op.drop_column('collateral_type')
        batch_op.drop_column('has_collateral')
        batch_op.drop_column('loan_term')
        batch_op.drop_column('loan_purpose')

    with op.batch_alter_table('borrowers', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('annual_revenue')
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_registration_number')
        batch_op.drop_column('business_name')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('monthly_income')
        batch_op.drop_column('work_address')
        batch_op.drop_column('job_title')
        batch_op.drop_column('employer_name')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('primary_id_number')
        batch_op.drop_column('primary_id_type')
        batch_op.drop_column('nin')
        batch_op.drop_column('bvn')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('email')
        batch_op.drop_column('date_of_birth')

    op.create_table('profile_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('document_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('document_data', sa.TEXT(), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['borrower_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('loan_purpose', sa.VARCHAR(length=18), nullable=False),
    sa.Column('loan_amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('loan_term', sa.INTEGER(), nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('has_collateral', sa.BOOLEAN(), nullable=True),
    sa.Column('collateral_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('collateral_value', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('collateral_description', sa.TEXT(), nullable=True),
    sa.Column('guarantor_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('guarantor_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('guarantor_address', sa.TEXT(), nullable=True),
    sa.Column('guarantor_relationship', sa.VARCHAR(length=50), nullable=True),
    sa.Column('application_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('application_date', sa.DATETIME(), nullable=False),
    sa.Column('approval_date', sa.DATETIME(), nullable=True),
    sa.Column('assigned_officer_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['borrower_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borrower_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('borrower_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('bvn', sa.VARCHAR(length=11), nullable=True),
    sa.Column('nin', sa.VARCHAR(length=11), nullable=True),
    sa.Column('primary_id_type', sa.VARCHAR(length=22), nullable=True),
    sa.Column('primary_id_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=13), nullable=True),
    sa.Column('employer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('work_address', sa.TEXT(), nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('employment_start_date', sa.DATE(), nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('business_registration_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('business_address', sa.TEXT(), nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('annual_revenue', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('profile_verification_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('bvn_verification_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('id_verification_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('employment_verification_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('borrower_id')
    )
    # ### end Alembic commands ###
